---
- name: Setup Kubernetes Cluster
  hosts: all
  become: true
  roles:
    - common

- name: Initialize Kubernetes Master
  hosts: master
  become: true
  roles:
    - master

- name: Join Kubernetes Worker Nodes
  hosts: worker
  become: true
  roles:
    - worker
