---
- name: Setup Kubernetes Cluster
  hosts: all
  become: true
  roles:
    - common

- name: Initialize Kubernetes Master
  hosts: k8s-master
  become: true
  roles:
    - master

- name: Join Kubernetes Worker Nodes
  hosts: k8s-node
  become: true
  roles:
    - worker
