---
- name: Install python3-kubernetes package
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present
    update_cache: true

- name: Check if Kubernetes is already initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_initialized

- name: Initialize Kubernetes
  ansible.builtin.command: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: kubeadm_init
  when: not k8s_initialized.stat.exists
  changed_when: "'kubeadm init' in kubeadm_init.stdout"

- name: Configure kubectl for root user
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy kubeconfig file
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    owner: root
    group: root
    mode: '0644'

- name: Check if Calico is already installed
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: kube-system
    name: calico-node
  register: calico_installed
  failed_when: false
  changed_when: false

- name: Apply Calico network plugin
  kubernetes.core.k8s:
    state: present
    src: https://docs.projectcalico.org/manifests/calico.yaml
  # Если Calico уже установлен, результат будет непустым (length != 0).
  when: k8s_initialized.stat.exists and (calico_installed.resources | length == 0)

# Получить команду для присоединения узлов к кластеру
- name: Get join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command
  changed_when: false

# Установить команду присоединения как факт
- name: Set join command as fact
  ansible.builtin.set_fact:
    kube_join_command: "{{ join_command.stdout }}"
